FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN pip install --upgrade pip wheel \
    && pip install "poetry==2.1.1" \
    && poetry config virtualenvs.create false

COPY poetry.lock pyproject.toml ./

RUN poetry install --with dev --no-interaction --no-ansi

COPY fastapi_app .
COPY tests ./tests

RUN chmod +x prestart.sh

RUN chmod +x run

ENTRYPOINT ["./prestart.sh"]

CMD ["./run"]
