volumes:
  pg_data:

networks:
  portfolio_dev:
    driver: bridge

services:

  pg:
    image: postgres:17.5
    env_file:
      - .env.deploy
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - portfolio_dev

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.deploy
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      pg:
        condition: service_healthy
    networks:
      - portfolio_dev

  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./
    env_file:
      - ./fastapi_app/.env.app
    depends_on:
      pg:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./fastapi_app
          target: /app
        - action: rebuild
          path: ./poetry.lock
    networks:
      - portfolio_dev

  nginx_internal:
    build:
      dockerfile: ./nginx/Dockerfile
      context: ./nginx
    ports:
      - "9000:80"
    depends_on:
      - backend
    restart: always
    networks:
      - portfolio_dev
