#volumes:
#  pgdata:
#
#services:
#
#  pg:
#    image: postgres:17.5
#    environment:
#      POSTGRES_DB: stock
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready" ]
#      interval: 5s
#      timeout: 3s
#      retries: 3
#
#  back:
#    build:
#      dockerfile: ./Dockerfile
#      context: ./
#    ports:
#      - "8000:8000"
#    depends_on:
#      pg:
#        condition: service_healthy
##    command:
##      - python
##      - run_main.py
##    develop:
##      watch:
##        - action: sync+restart
##          path: ./fastapi-application
##          target: /app
##        - action: rebuild
##          path: ./poetry.lock
#
##  adminer:
##    image: adminer
##    ports:
##      - "5055:80"
#
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: user@domain.com
#      PGADMIN_DEFAULT_PASSWORD: secretpassword
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#    ports:
#      - "5050:80"
#    depends_on:
#      pg:
#        condition: service_healthy