networks:
  portfolio_test:
    driver: bridge

services:

  pg_test:
    image: postgres:17.5
    environment:
      POSTGRES_DB: portfolio_test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user -d portfolio_test_db" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - portfolio_test

  backend_test:
    build:
      dockerfile: Dockerfile.test
      context: ./
    environment:
      APP_CONFIG__DB__URL: postgresql+asyncpg://test_user:test_password@pg_test:5432/portfolio_test_db
    volumes:
      - ./tests:/app/tests
    depends_on:
      pg_test:
        condition: service_healthy
    networks:
      - portfolio_test
    command: pytest -s --maxfail=5 -v
