# Dockerfile.worker
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app


RUN pip install --upgrade pip wheel \
    && pip install "poetry==2.1.1" \
    && poetry config virtualenvs.create false

COPY poetry.lock pyproject.toml ./

# (main + dev)
RUN poetry install --no-interaction --no-ansi

COPY fastapi_app ./

ENV PYTHONPATH=/app

CMD ["taskiq", "worker", "app.adapters.taskiq.broker:broker", "--worker", "1", "--fs-discover", "--tasks-pattern", "**/tasks"]
