"""Create stock transaction table

Revision ID: 7a70dc1e4482
Revises: 5fa8e2e104bc
Create Date: 2025-09-20 00:40:36.913069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a70dc1e4482"
down_revision: Union[str, Sequence[str], None] = "5fa8e2e104bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_trans",
        sa.Column("stock_tran_id", sa.Integer(), nullable=False),
        sa.Column("asset_type", sa.String(length=10), nullable=False),
        sa.Column("initial_price", sa.Float(), nullable=False),
        sa.Column("transaction_commission", sa.Float(), nullable=False),
        sa.Column(
            "transaction_currency", sa.String(length=10), nullable=False
        ),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("transaction_quantity", sa.Float(), nullable=False),
        sa.Column("transaction_type", sa.String(length=10), nullable=False),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("stock_tran_id", name=op.f("pk_stock_trans")),
    )
    op.create_index(
        op.f("ix_stock_trans_stock_tran_id"),
        "stock_trans",
        ["stock_tran_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stock_trans_stock_tran_id"), table_name="stock_trans"
    )
    op.drop_table("stock_trans")
    # ### end Alembic commands ###
