"""added enums to stock tran model

Revision ID: b6e8c2044ea3
Revises: fd079cb87322
Create Date: 2025-09-20 04:16:41.815679

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6e8c2044ea3"
down_revision: Union[str, Sequence[str], None] = "fd079cb87322"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# create ENUM objects SQLAlchemy
asset_type_enum = sa.Enum("stock", "etf", "bond", "crypto", name="asset_type_enum")
transaction_currency_enum = sa.Enum("USD", "EUR", "RUB", name="transaction_currency_enum")


def upgrade() -> None:
    """Upgrade schema."""
    # create ENUMs in db, if they don't exist
    asset_type_enum.create(op.get_bind(), checkfirst=True)
    transaction_currency_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_trans",
        "asset_type",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Enum(
            "stock", "etf", "bond", "crypto", name="asset_type_enum"
        ),
        existing_nullable=False,
        postgresql_using="asset_type::asset_type_enum",
    )
    op.alter_column(
        "stock_trans",
        "transaction_currency",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Enum("USD", "EUR", "RUB", name="transaction_currency_enum"),
        existing_nullable=False,
        postgresql_using="transaction_currency::transaction_currency_enum",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_trans",
        "transaction_currency",
        existing_type=sa.Enum(
            "USD", "EUR", "RUB", name="transaction_currency_enum"
        ),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    op.alter_column(
        "stock_trans",
        "asset_type",
        existing_type=sa.Enum(
            "stock", "etf", "bond", "crypto", name="asset_type_enum"
        ),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
    # drop ENUMs from db
    transaction_currency_enum.drop(op.get_bind(), checkfirst=True)
    asset_type_enum.drop(op.get_bind(), checkfirst=True)