"""changen stock tran model

Revision ID: fd079cb87322
Revises: 7a70dc1e4482
Create Date: 2025-09-20 03:35:33.923515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd079cb87322"
down_revision: Union[str, Sequence[str], None] = "7a70dc1e4482"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# create ENUM object SQLAlchemy
transaction_type_enum = sa.Enum("buy", "sell", name="transaction_type_enum")


def upgrade() -> None:
    """Upgrade schema."""
    # create ENUM in db, if it doesn't exist
    transaction_type_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_trans",
        "transaction_type",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Enum("buy", "sell", name="transaction_type_enum"),
        existing_nullable=False,
        postgresql_using="transaction_type::transaction_type_enum",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_trans",
        "transaction_type",
        existing_type=sa.Enum("buy", "sell", name="transaction_type_enum"),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
    # delete ENUM from db
    transaction_type_enum.drop(op.get_bind(), checkfirst=True)