"""add provider field  and uniq constraint to stocks

Revision ID: 17fae3873521
Revises: 2bba667978cd
Create Date: 2025-11-08 09:09:49.743661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17fae3873521"
down_revision: Union[str, Sequence[str], None] = "2bba667978cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stocks", sa.Column(
            "provider", sa.String(length=50),
            nullable=False,
            server_default="alphavantage",
        )
    )
    op.alter_column(
        "stocks", "name", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.create_unique_constraint(
        "uq_symbol_provider", "stocks", ["symbol", "provider"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_symbol_provider", "stocks", type_="unique")
    op.alter_column(
        "stocks", "name", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.drop_column("stocks", "provider")
    # ### end Alembic commands ###
